export const
  GRID_WIDTH = window.GRID_WIDTH,
  GRID_HEIGHT = window.GRID_HEIGHT,
  SCALE_FACTOR = 3,
  BLOCK_WIDTH = 16 * SCALE_FACTOR,
  WIDTH = GRID_WIDTH * BLOCK_WIDTH,
  HEIGHT = GRID_HEIGHT * BLOCK_WIDTH,
  CANVAS_WIDTH = window.innerWidth,
  CANVAS_HEIGHT = window.innerHeight,
  CENTER = [CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2],

  UPDATE_WAIT = 33,

  /// ARROW KEYS
  // KEY_RIGHT = 39,
  // KEY_LEFT = 37,
  // KEY_UP = 38,
  // KEY_DOWN = 40,

  /// WASD
  KEY_RIGHT = 68,
  KEY_LEFT = 65,
  KEY_UP = 87,
  KEY_DOWN = 83,

  GRID_COLOR = '#8e8e8e',

  HEALTH_BAR_COORDS = [100, 100],
  HEALTH_BAR_SIZE = [100, 500],
  HEALTH_BAR_COLOR = '#c0392b',

  BULLET_SPEED = 40,
  PLAYER_SPEED = 5
